name: luacheck

on: [push, workflow_dispatch]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4

      - name: build
        run: |
          luarocks install luacheck
          luarocks install busted

      - name: luacheck
        run: |
          luacheck

      - name: test
        run: |
          busted -o utfTerminal
